CREATE TABLE IF NOT EXISTS `type` (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    type VARCHAR(50) NOT NULL,
    PRIMARY KEY (id))
ENGINE = InnoDB;

START TRANSACTION;

INSERT INTO `type` (id, updated_at, `type`) VALUES (1, '2024-12-02 17:18:24', 'novel') ON DUPLICATE KEY UPDATE `type`=`type`;

COMMIT;